

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author user
 */

public class FrmLogin extends javax.swing.JFrame {
    private Banco banco;
    private GestorUsuarios gestor;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin(Banco banco, GestorUsuarios gestor) {
        initComponents();
        this.banco = banco;
        this.gestor =gestor;
    }

    private FrmLogin() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldContraseña = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonIniciarSesión = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jTextFieldUsuario.addActionListener(this::jTextFieldUsuarioActionPerformed);

        jButton1.setText("Salir");

        jButtonIniciarSesión.setText("Iniciar Sesión");
        jButtonIniciarSesión.addActionListener(this::jButtonIniciarSesiónActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText("Sistema Banco");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonIniciarSesión)
                                .addGap(44, 44, 44))
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldContraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonIniciarSesión))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesiónActionPerformed

        try {
            String usuario = jTextFieldUsuario.getText();
            String clave = jTextFieldContraseña.getText();

            if (usuario.isEmpty() || clave.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Usuario y contraseña son obligatorios",
                        "Campos Incompletos",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            Usuario usuarioAutenticado = gestor.acceder(usuario, clave);

            if (usuarioAutenticado != null) {
       
                abrirVentanaSegunTipo(usuarioAutenticado);
                jTextFieldUsuario.setText("");
                jTextFieldContraseña.setText("");
            } else {
                mostrarMensajeError();
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + ex.getMessage(),
                    "Error del Sistema",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_jButtonIniciarSesiónActionPerformed


    private void mostrarMensajeError() {
    javax.swing.JOptionPane.showMessageDialog(this,
            "ACCESO DENEGADO"
            + "Usuario o contraseña incorrectos.\n"
            + "Verifique sus credenciales e intente nuevamente.",
            "Error de Autenticación",
            javax.swing.JOptionPane.ERROR_MESSAGE);
}

    private void abrirVentanaSegunTipo(Usuario usuario) {
    String tipo = usuario.getTipoUsuario().toLowerCase();

    switch (tipo) {
        case "administrador":
        case "admin":
            // Abrir ventana de administrador
            FrmMenuAdmin ventanaAdmin = new FrmMenuAdmin(usuario, banco, gestor);
            ventanaAdmin.setVisible(true);
            break;

        case "empleado":
            // Abrir ventana de empleado
            if (usuario instanceof UsuarioEmpleado) {
                UsuarioEmpleado emp = (UsuarioEmpleado) usuario;
                FrmMenuEmpleado ventanaEmpleado = new FrmMenuEmpleado(emp, banco,gestor);
                ventanaEmpleado.setVisible(true);
            }
            break;

        case "cliente":
            // Abrir ventana de cliente
            if (usuario instanceof UsuarioCliente) {
                UsuarioCliente cli = (UsuarioCliente) usuario;
                FrmMenuCliente ventanaCliente = new FrmMenuCliente(cli, banco);
                ventanaCliente.setVisible(true);
            }
            break;

        default:
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Tipo de usuario no reconocido: " + tipo,
                    "Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
    }
}

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    Banco banco = new Banco();
    GestorUsuarios gestor = new GestorUsuarios();
    // Inicializar datos base del sistema
    inicializarDatos(banco, gestor);

    java.awt.EventQueue.invokeLater(() -> new FrmLogin(banco, gestor).setVisible(true));
}
    public static void inicializarDatos(Banco banco, GestorUsuarios gestor) {
        
    //Crear Cuentas
    
    Cuenta cuenta1=new Cuenta("001",2000);
    Cuenta cuenta2=new Cuenta("002",3000);
    //  Crear Clientes 
    Cliente c1 = new Cliente("Juan", "C-001", "Calle Villanueva", cuenta1);
    Cliente c2 = new Cliente("Ximena", "C-002", "Jiron Cusco", cuenta2);

    // Crear Empleados 
    Empleado e1 = new Empleado("Maria", "E-001", "Avenida Salomon");
    Empleado e2 = new Empleado("Carlos", "E-002", "Avenida Cayma");

    //  Registrar en Banco 
    banco.registrarCliente(c1);
    banco.registrarCliente(c2);
    banco.registrarEmpleado(e1);
    banco.registrarEmpleado(e2);

    // Crear Usuarios 
    UsuarioAdministrador admin = new UsuarioAdministrador("admin", "1234", true);
    UsuarioEmpleado ue1 = new UsuarioEmpleado("maria", "1234", e1);
    UsuarioEmpleado ue2 = new UsuarioEmpleado("carlos", "1234", e2);
    UsuarioCliente uc1 = new UsuarioCliente("juan", "1234", c1);
    UsuarioCliente uc2 = new UsuarioCliente("ximena", "1234", c2);

    
    // --- Registrar Usuarios en el Gestor ---
    gestor.registrarUsuario(admin);
    gestor.registrarUsuario(ue1);
    gestor.registrarUsuario(ue2);
    gestor.registrarUsuario(uc1);
    gestor.registrarUsuario(uc2);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIniciarSesión;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldContraseña;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
